version: "3.1"

services:
  database:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: productsDb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  databaseadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80
    depends_on:
      - database
